
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Мапим порт 8000 хоста на порт 8000 контейнера
    environment:
      - DB_PASSWORD=${DB_PASSWORD} # Передаём пароль для базы данных через переменную окружения
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=todoapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Мапим порт 5432 для доступа к базе данных с хоста (опционально)
    env_file:
      - .env
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    external: true

